name: delete-stix2-folder
on: workflow_dispatch

jobs:
  delete-stix2-folder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Delete stix2-objects and commit
        run: |
          rm -rf stix2_objects stix2_bundles
          git config user.name cve2stix
          git config user.email cve2stix@example.com
          git add .
          git commit -m "Delete stix2-objects"
          git push origin
