name: cve-download
on: 
  workflow_dispatch:
    inputs:
      start-date:
        type: string
        required: true
        default: "2021-01-01"
      end-date:
        type: string
        required: true
        default: "2021-12-31"

jobs:
  cve-download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run cve2stix
        run: |
          touch credentials.yml
          echo "$NVD_API_KEY" > credentials.yml
          python scripts/download-cves.py "${{ github.event.inputs.start-date }}" "${{ github.event.inputs.end-date }}"
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      - name: Push commits to repo
        run: |
          git push origin
